### ISSUE TITLE
Example to convert video?

### ISSUE THREAD

**Issue by zhwatts** [prouast/equirectangular-remap#1]
Hello,

This works great when input is an image file, however when input is a video it outputs blank (black) frames.

Your example is for an image, can you please provide an example for a video?

BTW, I am also using a 360fly camera, so I should be able to reproduce exactly.

**Comment by zhwatts** [comment]
figured it out:

ffmpeg -i file.mp4 -i x.pgm -i y.pgm -filter_complex remap,format=yuv444p,format=yuv420p out.mp4

**Comment by prouast** [comment]
Hi Zach,

sorry for the late reply - glad you worked it out. I usually use `ffmpeg -i spherical.mp4 -i x.pgm -i y.pgm -lavfi remap equirectangular_yuv444p.mp4`

Best,
Philipp
